### ISSUE TITLE
Fazer um único sprite ao invés de vários

### ISSUE THREAD

**Issue by andregumieri** [guminidigital/front-boilerplate#10]
Conforme documentado no issue #9 fazer o formato de múltiplos sprites está gerando conflitos e sobrescrevendo variáveis e mixins do less. Sendo assim, para a versão 1.0.0, vamos seguir com um sprite único.

**Comment by rflgentil** [comment]
André, olhei bem rápido mas achom que isso é simples de resolver. 

https://github.com/twolfson/gulp.spritesmith#variable-mapping

**Comment by andregumieri** [comment]
Hummm, legal, @rflgentil. Estava procurando errado. Vou dar uma olhada nisso então

**Comment by andregumieri** [comment]
O Issue #9 foi resolvido, invalidando este issue.
