### ISSUE TITLE
Criar task de sprite

### ISSUE THREAD

**Issue by andregumieri** [guminidigital/front-boilerplate#3]

**Comment by andregumieri** [comment]
Estava pensando aqui na estrutura de pasta do sprite. Em src poderia ser algo do genero:

src/images/sprite-nome-do-sprite/_.png
src/images/sprite-nome-do-outro-sprite/_.png

O GULP interpreta tudo que for images/sprite_/_.png como sprite e no dist gera:

dist/images/sprite-nome-do-sprite.png
dist/images/sprite-nome-do-outro-sprite.png

O que acham?

**Comment by rflgentil** [comment]
pode ser!

**Comment by andregumieri** [comment]
@rflgentil Testei aqui mas não rolou :( Não está gerando os sprites. Eu reverti o branch _develop_ para o commit de antes do sprite e criei um branch _task-sprites_ com o seu código para depois poder verificar.

**Comment by rflgentil** [comment]
Tem que criar uma pasta dentro da pasta _sprites_ para cada sprite nova que você quer gerar.

**Comment by andregumieri** [comment]
Agora foi @rflgentil! Vacilo meu. Ficou ótimo! Só acho que algumas coisas de estrutura é interessante mudar para ficar no formato _src/_ = _dist/_.

Se foi criada uma pasta dentro de sprites, tipo _./src/sprites/home/*.png_, na dist ela deve estar na mesma estrutura. Claro que não criando uma pasta para um arquivo único, mas sair como _./dist/sprites/home.png_

Para o CSS, como ainda não sentamos para discutir a metodologia de estruturação de pastas, acho que por enquanto é melhor manter o CSS dentro de ./src/css/inc/sprites/nome-do-sprite.less. No dist esta pasta não deve ser copiada.

**Comment by rflgentil** [comment]
Eu pensei em deixar os sprites no mesmo nível das outras imagens, mas vou mudar pra criar a pasta _sprites_ dentro de dist.

O CSS eu criei a pasta _base_ justamente já pensando na estrutura que vamos adotar. Inclusive estou devendo as referencias pra vocês.

**Comment by andregumieri** [comment]
@rflgentil faz sentido seu pensamento, mas é mais uma questão de explicitar o significado de cada coisa, saca? 

Vamos ter uma reunião em breve que vamos conversar sobre isso. Na mesma lógica de deixar as coisas mais explicitas, é legal mudar de base para sprites :)

**Comment by andregumieri** [comment]
Passado para issue #11
